[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# evm_version = "berlin"
# gas_price = 1000000000000000000
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[lint]
exclude_lints = ["mixed-case-function","screaming-snake-case-immutable", "unaliased-plain-import", "mixed-case-variable"]
