[tools]
rust = { version = "1.86.0" }

[tasks.dockerBuild]
alias = "db"
run = 'docker build . -t auction_controller:base "$@"'

[tasks.dockerRun]
alias = "dr"
run = 'docker run --rm auction_controller:base  "$@"'

[tasks.podmanBuild]
alias = "pb"
run = 'podman build . -t auction_controller:base "$@"'

[tasks.podmanRun]
alias = "pr"
run = 'podman run --rm auction_controller:base "$@"'

[tasks.dockerPush]
alias = "dp"
run = "docker image tag auction_controller:base ar33d/auction_controller:base && docker push ar33d/auction_controller:base"
