#![allow(unused_imports, clippy::all, rustdoc::all)]
#![allow(unused)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod r#address;
pub mod r#auction;
pub mod r#erc165;
pub mod r#erc20;
pub mod r#erc721;
pub mod r#erc721_metadata;
pub mod r#i_uniswap_v2_router02;
pub mod r#nft_collection;
pub mod r#safe_math;
pub mod r#sapi_coin;
pub mod r#std_constants;
pub mod r#strings;
pub mod r#token;
pub mod r#tokenomics420;
